dist: trusty
sudo: required
language: swift
xcode_workspace: NovelReader.xcworkspace
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
xcode_scheme: NovelReader
before_install:
- pod --version
- pod setup --silent > /dev/null
- pod repo update --silent
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks
script:
- xcodebuild clean build -workspace "NovelReader.xcworkspace" -scheme "NovelReader" -configuration Release -sdk iphonesimulator | xcpretty -c
- sonar-scanner -X
after_success:
- bash <(curl -s https://codecov.io/bash)
