language: swift
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
xcode_scheme: NovelReader
xcode_workspace: NovelReader.xcworkspace # path to your xcodeproj folder
script:
 #- xcodebuild -scheme NovelReader  -sdk "iphonesimulator" -configuration Release -arch x86_64 -arch i386 only_active_arch=no defines_module=yes
 #- xcodebuild -workspace "FTMobileCoreSampleWorkspace.xcworkspace" -scheme FTMobileCoreSample -sdk "iphoneos" -configuration Release -arch arm64 -arch armv7 -arch armv7s only_active_arch=no defines_module=yes
 #Without pod dependency 
 #- xcodebuild -project NovelReader.xcodeproj -scheme NovelReader -arch x86_64 -arch i386 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build | xcpretty -c
 - xcodebuild -scheme NovelReader -workspace "NovelReader.xcworkspace" -sdk iphonesimulator build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
