dist: trusty
sudo: required
language: swift
xcode_workspace: NovelReader.xcworkspace
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
xcode_scheme: NovelReader
before_install:
- pod --version
- pod setup --silent > /dev/null
- pod repo update --silent
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks
script:
- xcodebuild clean build -workspace "NovelReader.xcworkspace" -scheme "NovelReader" -configuration Release -sdk iphonesimulator | xcpretty -c
- sonar-scanner -X
addons:
  sonarcloud:
    organization: ppraveentr-github
    token:
      secure: jIWNRFBlFJIXWwo8i7IuJmV7ASB0B0RyqGzZJAMx9Zp8ZcTBeScu1MH9QjsU6UTwkyg/mfrH99BrDhzcPhStY1Su0Q9zMu150bQwLDSL98VznyBc7vUL/DfxEy6yZNfc9JzZ9fsBlP6BKGs5dlRzyk2Fc4CkbdKWLUUPA6mqu/GECsAG3aDAc6xAgkWUo/spif8dTw1YwQsj8df/O6IIoZ/PAibIseYgndlMQr9w2tRIeY+zrQiZ9wtd/Dpmt66Y3/qDZ9YEMooFpdIYLRWKrNEvXa3Z+7Swq4rtPlJkF+5COP16uEzKJtOR6uNdTjHgxQ/AGmJj4GJqk2aHsAPowLJKFWqQdcw4brCOVeNf9ZZMWK5PhwqxFa7wcYAaMQQ6AzFP/iJNk4lYlOZNYF5eOoqY3UCqnsPPNBbcamt8tEWOpHRmB1HmDlpRa3cg3WRLpc+YopM8k9lLaHuL6scKuahA9oVkvJfxShTauIqlsIQJxkdOmF99kHAQZZ00gg5xlaNMZ9CI+DI2f7vy0AwvKLlpGsNJ/dxrjPh+urE9V+VHP50rbFgQ6KZGAm6J4NwMhdI1mZZErOAxSk20Z6NFliqQpztCoOl3EoKTAG+adY9RoOcnAp3sHbl5UdA13634HNspOyFf5Ewn7LI7FaMMtdn7aKtZyyjeFhUmGIr65wE=
env:
  global:
  - secure: jIWNRFBlFJIXWwo8i7IuJmV7ASB0B0RyqGzZJAMx9Zp8ZcTBeScu1MH9QjsU6UTwkyg/mfrH99BrDhzcPhStY1Su0Q9zMu150bQwLDSL98VznyBc7vUL/DfxEy6yZNfc9JzZ9fsBlP6BKGs5dlRzyk2Fc4CkbdKWLUUPA6mqu/GECsAG3aDAc6xAgkWUo/spif8dTw1YwQsj8df/O6IIoZ/PAibIseYgndlMQr9w2tRIeY+zrQiZ9wtd/Dpmt66Y3/qDZ9YEMooFpdIYLRWKrNEvXa3Z+7Swq4rtPlJkF+5COP16uEzKJtOR6uNdTjHgxQ/AGmJj4GJqk2aHsAPowLJKFWqQdcw4brCOVeNf9ZZMWK5PhwqxFa7wcYAaMQQ6AzFP/iJNk4lYlOZNYF5eOoqY3UCqnsPPNBbcamt8tEWOpHRmB1HmDlpRa3cg3WRLpc+YopM8k9lLaHuL6scKuahA9oVkvJfxShTauIqlsIQJxkdOmF99kHAQZZ00gg5xlaNMZ9CI+DI2f7vy0AwvKLlpGsNJ/dxrjPh+urE9V+VHP50rbFgQ6KZGAm6J4NwMhdI1mZZErOAxSk20Z6NFliqQpztCoOl3EoKTAG+adY9RoOcnAp3sHbl5UdA13634HNspOyFf5Ewn7LI7FaMMtdn7aKtZyyjeFhUmGIr65wE=
after_success:
- bash <(curl -s https://codecov.io/bash)
